{
 "title": "Pravega Operation dashboard",
 "tags": [
  "pravega",
  "imported"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "SHOW TAG VALUES WITH KEY=\"host\""
   },
   {
    "name": "retention",
    "query": "SHOW RETENTION POLICIES ON pravega"
   }
  ]
 },
 "panels": [
  { "title": "Latency Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Segment Write Latency (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pravega_segmentstore_segment_write_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Write Latency (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pravega_segmentstore_storage_write_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "BK Write Latency (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pravega_segmentstore_bookkeeper_write_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "BK Total Write Latency (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pravega_segmentstore_bookkeeper_total_write_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Segment Read Latency (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pravega_segmentstore_segment_read_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Read Latency (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pravega_segmentstore_storage_read_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Segment Write Errors (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pravega_segmentstore_segment_write_latency_ms_fail_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Write Errors (p0.99)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pravega_segmentstore_storage_write_latency_ms_fail_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "phi", "operator": "=", "value": "0.99" },
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  { "title": "Throughput Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Segment Write Bytes/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "sum(segment_write_bytes.Rate)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "segmentstore_stream_write_bytes",
     "query": "SELECT sum(\"mean_rate\") FROM (SELECT mean(\"Rate\") as \"mean_rate\" FROM \"$retention\".\"segmentstore_stream_write_bytes\" WHERE $timeFilter GROUP BY time($__interval), \"scope\", \"stream\" ) GROUP BY time($__interval) fill(null)\n"
    },
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "segmentstore_global_write_bytes",
     "select": [
      [
       { "params": [ "Rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Segment Read Bytes/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "sum(segment_read_bytes.Rate)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "segmentstore_stream_read_bytes",
     "query": "SELECT sum(\"mean_rate\") FROM (SELECT mean(\"Rate\") as \"mean_rate\" FROM \"$retention\".\"segmentstore_stream_read_bytes\" WHERE $timeFilter GROUP BY time($__interval), \"scope\", \"stream\" ) GROUP BY time($__interval) fill(null)\n"
    },
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "segmentstore_global_read_bytes",
     "select": [
      [
       { "params": [ "Rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Write Bytes/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "segmentstore_storage_write_bytes",
     "select": [
      [
       { "params": [ "Rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Read Bytes/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "segmentstore_storage_read_bytes",
     "select": [
      [
       { "params": [ "Rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  { "title": "Segment Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Segment Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_write_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Segment Write Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_write_latency_ms_fail_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Segment Read Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_read_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Segment Read Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_read_latency_ms_fail_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  { "title": "Storage Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Storage Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_write_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Read Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_read_latency_ms_fail_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Read Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_read_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Write Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_storage_write_latency_ms_fail_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  { "title": "Container Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Container Operation Processor Delay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_container_operation_processor_delay_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Container Operation Queue Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_container_operation_queue_size_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Container Operation Commit Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_container_operation_commit_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Container Operation Commit Memory Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_container_operation_commit_memory_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Container Operation Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_container_operation_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "Container Operation Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_container_operation_latency_ms_fail_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  { "title": "BK Writes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "BK Write Bytes/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "segmentstore_bookkeeper_write_bytes",
     "select": [
      [
       { "params": [ "Rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "BK Ledger Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "c$tag_container",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_bookkeeper_ledger_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "BK Write Queue Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_bookkeeper_write_queue_size_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "BK Write Queue Fill",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_bookkeeper_write_queue_fill_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "BK Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_bookkeeper_write_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "BK Write Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_bookkeeper_write_latency_ms_fail_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "BK Total Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_bookkeeper_total_write_latency_ms_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  },
  {
   "title": "BK Total Write Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "p$tag_phi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "phi" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_bookkeeper_total_write_latency_ms_fail_percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*$host.*/" }
     ]
    }
   ]
  }
 ]
}