status_html: ../data/p3_test_driver/data/status/pravega.html
test_driver_log_filename: ../data/p3_test_driver/data/logs/p3_test_driver.log
ssh_user: ec2-user
ssh_identity_file: /home/faheyc/.ssh/pravega_aws
kubernetes: false
docker: false
aws-ec2: true
terraform: true
ansible: true

